name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push k3s image 
        run: | 
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
          kubectl apply -f ./kubs/db.yaml --validate=false
          kubectl apply -f ./kubs/redis.yaml
          kubectl apply -f ./kubs/saleor-api.yaml
          kubectl apply -f ./kubs/saleor-dashboard.yaml
          kubectl apply -f ./kubs/saleor-worker.yaml
            
            
